#! /bin/sh

# Copyright (C) 2004 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


test -z "$QA_SKIP_BUILD_ROOT" || exit 0

if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
        exit 0
fi

tmp=$(mktemp /tmp/cbr.XXXXXX)
trap "rm -f $tmp" EXIT

find "$RPM_BUILD_ROOT" -type f -print0 | LANG=C xargs -0r grep "$RPM_BUILD_ROOT" >$tmp

test -s "$tmp" && {
    cat "$tmp"
    echo $"Found '$RPM_BUILD_ROOT' in installed files; aborting"
    exit 1
} || :
