#! /bin/bash
# $Id: check-rpaths-worker,v 1.2 2004/05/12 06:02:15 scop Exp $

# Copyright (C) 2004 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


fail=
IFS=:

function msg()
{
    local val=$1
    local cmp=$2
    local msg=
    local fail=

    test $[ $val & $cmp ] -ne 0 || return 0

    if test $[ $val & ~$QA_RPATHS ] -eq 0; then
	msg=WARNING
    else
	msg=ERROR
	fail=1
    fi

    shift 2
    echo "$msg: $@" >&2

    test -z "$fail"
}

: ${QA_RPATHS:=0}

for i; do
    set -- $(readelf -d "$i" 2>/dev/null | LANG=C sed -e 's!.*(RPATH).*: \[\(.*\)\]!\1!p;d') || :
    for j; do
	case x"$j" in
	    (x/lib/*|x/usr/lib/*|x/usr/X11R6/lib/*|x/usr/local/lib/*)
		badness=0;;
	    (x/lib64/*|x/usr/lib64/*|x/usr/X11R6/lib64/*|x/usr/local/lib64/*)
		badness=0;;
	    (\$*)
		badness=0;;
		
	    (x/lib|x/usr/lib|x/usr/X11R6/lib)
	    	badness=1;;
	    (x/lib64|x/usr/lib64|x/usr/X11R6/lib64)
		badness=1;;
		
	    (x|x.)
		badness=4;;
	    *)	badness=2;;
	esac

	base=${i##$RPM_BUILD_ROOT}
	msg "$badness" 1 "file '$base' contains a standard rpath '$j'"  || fail=1
	msg "$badness" 2 "file '$base' contains an invalid rpath '$j'"  || fail=1
	msg "$badness" 4 "file '$base' contains an insecure rpath '$j'" || fail=1
    done
done

test -z "$fail"
