#!/bin/bash

# $Id: fedora-newrpmspec,v 1.4 2005/03/24 16:32:39 scop Exp $

SPEC="/usr/share/fedora/spectemplate-minimal.spec"

newrpmspec.help() {
	echo "fedora-newrpmspec creates a new Fedora spec template"
	echo ""
	echo "Usage:"
	echo "fedora-newrpmspec               without parameter creates a spec template"
	echo "                                called newpackage.spec"
	echo "fedora-newrpmspec <app name>    creates a spec template for <app name>"
        echo "                                called <app name>.spec"	
	echo "fedora-newrpmspec -h|--help     show this usage information"
	exit 42
}

newrpmspec.default() {

if [ "$1" = "" ]; then 
	if [ -f newpackage.spec ]; then
    		echo "newpackage.spec already exists.  Exiting."
	else
    		echo "RPM spec template has been copied to newpackage.spec."
    		cp $SPEC newpackage.spec
	fi
else
	if [ -f $1.spec ]; then
		echo "$1.spec already exists.  Exiting."
	else
		cat $SPEC | sed -e "s/^\\(Name:\\s*\\)/\\1$1/" > $1.spec
		echo "RPM spec template has been copied to $1.spec."
	fi
fi
exit 42
}

case $1 in

-h|--help)
	newrpmspec.help
	;;
*)	
	newrpmspec.default $1
	;;
esac

