#!/bin/bash

# fedora-kmodhelper - Helper script for building kernel module RPMs
# Copyright (c) 2003-2004 Ville Skyttä <ville.skytta@iki.fi>,
#                         Thorsten Leemhuis <fedora@leemhuis.info>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# $Id: fedora-kmodhelper,v 1.4 2004/01/29 20:40:10 scop Exp $

myprog="fedora-kmodhelper"
myver="0.9.6"
variants='\(BOOT\|\(big\|huge\)mem\|debug\|enterprise\|smp\|uml\)'
var=

cc=
config=
cflags=
cpu=
modflags=
rhkernel=
rhmodflags=
srcdir=
uname=
unamefromsrc=
variant=
verrel=
version=

get_uname ()
{
  [ -n "${uname}" ] || uname=`uname -r`
}
get_unamefromsrc ()
{
  if [ -z "${srcdir}" -o -z "${config}" ] ; then
    echo "At least srcdir (-s) and config (-f) needed, aborting."
    return 1
  fi
  cd "${srcdir}" && \
  unamefromsrc=`( sed 's|\.config\b|'${config}'|g' Makefile && \
    echo -e '\n'${myprog}'-kernelrel:\n\t@echo $(KERNELRELEASE)\n' ) \
  | make -f - ${myprog}-kernelrel` && \
  cd -
  get_rhkernel || return $?
  get_verrel || return $?
  # If it's a RH/FC kernel and verrel doesn't end with "custom", strip it.
  if [ "${rhkernel}" = "true" ] && ! echo "${verrel}" | grep -q 'custom$'; then
    unamefromsrc="${unamefromsrc%%custom}"
  fi
}
get_cpu ()
{
  [ -z "${cpu}" ] || return 0
  get_uname || return $?
  cpu=`rpm -q --queryformat '%{ARCH}' "kernel-${uname}" 2>/dev/null`
  [ $? -eq 0 ] || cpu=
  # Note: calling get_cflags here will result in a loop if $config is not set.
  if [ -z "${cpu}" -a -n "${config}" ] ; then
    get_cflags || return $?
    cpu=`echo ${cflags} | sed 's/^.*-march=\([^[:space:]]*\).*$/\1/'`
    [ "${cpu}" != "${cflags}" ] || cpu=
  fi
  [ -n "${cpu}" ] || cpu=`uname -m`
}
get_verrel ()
{
  [ -z "${verrel}" ] || return 0
  get_uname || return $?
  verrel=`echo "${uname}" | sed 's/'${variants}'$//'`
}
get_version ()
{
  [ -z "${version}" ] || return 0
  get_uname || return $?
  version=`echo "${uname}" | sed 's/-[^-]*$//'`
}
get_variant ()
{
  [ -z "${variant}" ] || return 0
  get_uname || return $?
  local kv=`echo ${uname} | sed 's/^.*'${variants}'$/\1/'`
  [ "${kv}" = "${uname}" ] || variant="${kv}"
}
get_srcdir ()
{
  if [ -n "${srcdir}" ] ; then
    if [ ! -d "${srcdir}" -a ! -h "${srcdir}" ] ; then
      echo "Error: source dir '${srcdir}' not found." >&2
      return 1
    fi
  else
    get_verrel || return $?
    get_uname # || return $?
    for dir in "/usr/src/linux-${verrel}" "/lib/modules/${uname}/build"; do
      if [ -d "${dir}" -o -h "${dir}" ] ; then
        if [ -e "${dir}/include/linux" ] ; then
          srcdir="${dir}"
          return 0
        else
          echo "Warning: dir '${dir}' doesn't look like a source dir." >&2
        fi
      else
        echo "Warning: source dir '${dir}' not found." >&2
      fi
    done
    echo "Error: could not find a source dir." >&2
    return 1
  fi
}
get_rhkernel ()
{
  get_srcdir || return $?
  if grep rhconfig\\.h "${srcdir}/include/linux/autoconf.h" &>/dev/null ; then
    rhkernel=true
  else
    rhkernel=false
  fi
}
get_config ()
{
  if [ -n "${config}" ] ; then
    if [ ! -e "${config}" ] ; then
      echo "Error: config file doesn't exist: '${config}'." >&2
      return 1
    fi
  else
    get_cpu || return $?
    get_srcdir || return $?
    get_version || return $?
    get_rhkernel || return $?
    if [ "${rhkernel}" = "true" ] ; then
      get_variant || return $?
      config="${srcdir}/configs/kernel-${version}-${cpu}${variant:+-${variant}}.config"
      if [ ! -e "${config}" ] ; then
        echo "Warning: config file doesn't exist: '${config}'." >&2
        get_uname || return $?
        config="/boot/config-${uname}"
        echo "Warning: falling back to '${config}'." >&2
      fi
      if [ ! -e "${config}" ] ; then
        echo "Warning: config file doesn't exist: '${config}'." >&2
        echo "Error: could not find a config file." >&2
        unset config
        return 1
      fi
    else
      config="${srcdir}/.config"
      if [ ! -e "${config}" ] ; then
        echo "Warning: config file doesn't exist: '${config}'." >&2
        echo "Error: could not find a config file." >&2
        unset config
        return 1
      fi
    fi
  fi
}
get_cc ()
{
  get_config || return $?
  get_srcdir || return $?
  cd "${srcdir}" && \
  cc=`( sed 's|\.config\b|'${config}'|g' Makefile && \
    echo -e '\n'${myprog}'-cc:\n\t@echo $(CC)\n' ) \
  | make -f - ${myprog}-cc` && \
  cd -
}
get_cflags ()
{
  get_config || return $?
  get_srcdir || return $?
  cd "${srcdir}" && \
  cflags=`( sed 's|\.config\b|'${config}'|g' Makefile && \
    echo -e '\n'${myprog}'-cflags:\n\t@echo $(CFLAGS)\n' ) \
  | make -f - ${myprog}-cflags` && \
  cd -
}
get_modflags ()
{
  get_config || return $?
  get_srcdir || return $?
  cd "${srcdir}" && \
  modflags=`( sed 's|\.config\b|'${config}'|g' Makefile && \
    echo -e '\n'${myprog}'-modflags:\n\t@echo $(MODFLAGS)\n' ) \
  | make -f - ${myprog}-modflags` && \
  cd -
}
get_rhmodflags ()
{
  [ -z "${rhmodflags}" ] || return 0
  get_rhkernel || return $?
  [ -n "${rhkernel}" ] || return 0
  get_variant || return $?
  get_cpu || return $?
  local rhvariant=`echo ${variant:-UP} | tr a-z A-Z`
  rhmodflags="-DMODULE=1 -D__BOOT_KERNEL_H_ -D__MODULE_KERNEL_${cpu}=1 -D__BOOT_KERNEL_${rhvariant}=1"
}
get_allcflags ()
{
  get_cflags || return $?
  get_modflags || return $?
  get_rhmodflags || return $?
  echo "${cflags} ${modflags} ${rhmodflags}" | sed 's/[[:space:]]*$//'
}
get_diag ()
{
  # Some distance to rpmbuild output
  echo
  if [ -z "${srcdir}" ] ; then
    cat <<EOF >&2
srcdir was not specified, and I was unable to determine it myself.
Output from command "$(basename $0) srcdir -u ${uname:-$(uname -r)}":
# Start
EOF
    bash ${0} srcdir -u "${uname:-$(uname -r)}" >&2
    cat <<EOF >&2
# End

Please provide the source dir with the -s option and/or provide the kernel
uname with the -u option.

Aborting.

EOF
    return 128
  fi

  if [ -z "${cpu}" -o -z "${uname}" ] ; then
    cat <<EOF >&2
At least srcdir, uname and arch required.

Aborting.

EOF
    return 128
  fi

  if ! get_config ; then
    cat <<EOF >&2
Could not find kernel config file.  Maybe the chosen variant does not exist?

Aborting.

EOF
    return 128
  fi

  get_verrel
  get_unamefromsrc
  if [ "${unamefromsrc}" != "${verrel}" ] ; then
    cat <<EOF >&2
Error: resolved "verrel" (${verrel}) and the uname resolved from sources
(${unamefromsrc}) do not match.  Please provide the correct uname with the
-u option.

Aborting.

EOF
    return 1
  fi

  if get_rhkernel && [ "${rhkernel}" = "true" ] ; then
    local providedcpu="${cpu}"
    cpu=""
    get_cpu
    if [ "${providedcpu}" != "${cpu}" ] ; then
      cat <<EOF >&2
Warning:  you provided the target CPU "${providedcpu}" but are running a
kernel built for "${cpu}".  Changes are that the resulting binaries will not
work with this kernel.
EOF
      [ -z "${nowait}" ] && sleep 10
    fi
    cpu="${providedcpu}"
    unset providedcpu
  fi

  for i in variant version config cc rhmodflags variant ; do
    get_"${i}"
    local errorlevel=$?
    if [ $errorlevel -gt 0 ] ; then
      echo "Error: get_${i} returned $errorlevel.  Aborting." >&2
      exit 1
    fi
  done

  cat <<EOF
Modules will be built with these settings, make sure they are correct:

Version:                        ${version}
Uname:                          ${uname}
Kernel Compiler:                ${cc}
Target CPU:                     ${cpu}
Kernel Source dir:              ${srcdir}
EOF
  if [ "${config}" = "${config##${srcdir}}" ] ; then
    echo "Config File Name:               ${config}"
  else
    echo "Config File Name:               \$srcdir${config##${srcdir}}"
  fi
  echo "Redhat/Fedora Kernel:           ${rhkernel}"
  if [ "${rhkernel}" = "true" ] ; then
    cat <<EOF
Redhat/Fedora Kernel Release:   ${verrel}
Redhat/Fedora Kernel Variant:   ${variant:-(none -- kernel is UP)}
Redhat/Fedora special MODFLAGS: ${rhmodflags}
EOF
  fi
  echo
}
usage ()
{
  cat <<EOF
You called: $(basename ${0}) ${invocation}

Usage: ${myprog} <command> <option>+
 Commands:
  cc                 - Get compiler.
  config             - Get config file name.
  cpu                - Get target CPU.
  cflags             - Get kernel CFLAGS.
  modflags           - Get module CFLAGS.
  rhmodflags         - Get RH/FC specific module CFLAGS.
  allcflags          - Get all CFLAGS (cflags, modflags, rhmodflags).
  srcdir             - Get source dir.
  uname              - Get uname.
  variant            - Get variant (bigmem, smp etc).
  verrel             - Get "base" version-release.
  version            - Get "base" version.
  rhkernel           - "true" if the source tree is a RH/FC one.
  diag               - Check settings and output a brief overview.
 Options:
  -s|--srcdir <dir>  - Source directory.
  -p|--cpu <cpu>     - Target CPU. The default is resolved based
                       on the running kernel.
  -u|--uname <uname> - Target uname.  The default is $(uname -r).
  -f|--config <file> - Configuration file.
                       If set, CPU and uname are ignored.
     --nowait        - Do not wait if "diag" fins something unusual.
  -h|-?|--help       - Output this help and exit.
  -V|--version       - Output version number and exit.
EOF
}

invocation="$(basename ${0}) $@"
while [ "${1}" ] ; do
  case "${1}" in
    allcflags|cc|cflags|config|cpu|diag|modflags|rhkernel|rhmodflags|srcdir|uname|variant|verrel|version)
      var="${1}"
      ;;
    -s|--srcdir)
      shift
      srcdir="${1}"
      ;;
    -p|--cpu)
      shift
      cpu="${1}"
      ;;
    -u|--uname)
      shift
      uname="${1}"
      ;;
    -f|--config)
      shift
      config="${1}"
      ;;
    -h|--help|-?)
      usage >&2
      exit 0
      ;;
    -V|--version)
      echo "${myprog} ${myver}"
      exit 0
      ;;
    --nowait)
      nowait="true"
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ -z "${var}" ] ; then
  echo "Error: command not specified." >&2
  usage >&2
  exit 2
fi

get_"${var}" || exit $?
[ -z "${!var}" ] || echo "${!var}"

# Local variables:
# mode: sh
# sh-indentation: 2
# indent-tabs-mode: nil
# End:
# ex: ts=4 sw=4 et
