#!/bin/sh
#
# fedora-installdevkeys
#
# Author:  Warren Togami <warren@togami.com>
# License: GPL

echo "Fedora Trusted GPG Key Installer"
echo "   This script will install trusted GPG keys into an alternate RPM keyring."
echo "   This allows you to easily check signatures of packages without the risk of "
echo "   installing extra keys in your system RPM keyring."
echo 
if [ "$(whoami)" != "root" ]; then
    echo "Installing alternate RPM keyring in ~/.fedorarpm"
    RPMROOT=~/.fedorarpm
else
    echo "Installing alternate RPM keyring in /var/fedora/rpm"
    RPMROOT=/var/fedora/rpm
fi
mkdir -p $RPMROOT

echo "pub  1024D/DB42A60E 1999-09-23 Red Hat, Inc <security@redhat.com>"
echo "     Key fingerprint = CA20 8686 2BD6 9DFC 65F6  ECC4 2191 80CD DB42 A60E"
echo "sub  2048g/961630A2 1999-09-23"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY

echo "pub  1024D/897DA07A 2002-03-15 Red Hat, Inc. (Beta Test Software) <rawhide@redhat.com>"
echo "     Key fingerprint = 17E8 543D 1D4A A5FA A96A  7E9F FD37 2689 897D A07A"
echo "sub  1024g/9E774FDD 2002-03-15"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-beta

echo "pub  1024D/E418E3AA 2003-08-20 Red Hat, Inc. automated build signing key (2003) <rawhide@redhat.com>"
echo "     Key fingerprint = A4ED 786E 361F 3A86 7FFD  193F 94CD 5742 E418 E3AA"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-rawhide

echo "pub  1024D/4F2A6FD2 2003-10-27 Fedora Project <fedora@redhat.com>"
echo "     Key fingerprint = CAB4 4B99 6F27 744E 8612  7CDF B442 69D0 4F2A 6FD2"
echo "sub  1024g/FB939E34 2003-10-27"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-fedora

echo "pub  1024D/30C9ECF8 2003-10-27 Fedora Project (Test Software) <rawhide@redhat.com>"
echo "     Key fingerprint = 3166 C14A AE72 30D9 3B7A  B2F6 DA84 CBD4 30C9 ECF8"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-fedora-test

echo "pub  1024D/1CDDBCA9 2003-10-27 Fedora Project automated build signing key (2003) <rawhide@redhat.com>"
echo "     Key fingerprint = 2312 6DEE 2014 B8A7 6CD6  D32C E138 5D4E 1CDD BCA9"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-fedora-rawhide

echo "pub  1024D/8DF56D05 2003-03-27 Fedora Linux (RPMS) <security@fedora.us>"
echo "     Key fingerprint = B5BD CEB2 8F0D 54DE 6F4D  2275 29D5 BA24 8DF5 6D05"
echo "sub  2048g/6E208B8B 2003-03-27"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-fedora.us

echo "pub  1024D/1AC70CE6 2004-12-14 Fedora Pre Extras Release <pre-extras@fedoraproject.org>"
echo "     Key fingerprint = 5389 DD00 C5BC 5168 12B4  3272 82ED 9504 1AC7 0CE6"
echo "uid                            Fedora Project <fedora-extras@redhat.com>"
echo "uid                            Fedora Project <fedora-extras@fedoraproject.org>"
echo "sub  1024g/4E1A9D43 2004-12-14"
rpm --root $RPMROOT --import /usr/share/fedora/devgpgkeys/RPM-GPG-KEY-fedora-extras

echo
echo "   Installation complete within $RPMROOT.  You may now use the following command:"
echo "       fedora-rpmchecksig <packages>"
echo
