#!/bin/sh

#
# fedora-rmdevelrpms -- Find (and optionally remove) "development" RPMs
#
# Author:  Ville Skyttä <ville.skytta at iki.fi>
# License: GPL
# $Id: fedora-rmdevelrpms,v 1.5 2003/10/02 20:38:12 scop Exp $
#
# This script is useful in cleaning up development RPMs from your system,
# eg. when starting to make a new RPM package.
#
# Currently, "development RPMs" include:
# - Any package whose %{NAME} ends with "-devel", except gcc requirements.
# - Ones listed in $DEVPKGS below.
# - Ones in $ADDITIONAL_DEVEL_RPMS (see below).
#
# If you want to keep some devel RPMs around, put their names into the
# $KEEP_DEVEL_RPMS environment variable, separated by space.  The opposite
# of this is provided by $ADDITIONAL_DEVEL_RPMS.
#
# You can persist these settings in the system-wide configuration file
# /etc/fedora/develrpms.conf or a per-user ~/.develrpmsrc.

if [ -r /etc/fedora/develrpms.conf ]; then
    . /etc/fedora/develrpms.conf
fi
if [ -r $HOME/.develrpmsrc ]; then
    . $HOME/.develrpmsrc
fi

DEVPKGS="autoconf autoconf213 automake automake14 automake15 automake16 bison byacc compat-gcc compat-gcc-c++ compface dev86 djbfft docbook-utils-pdf doxygen flex gettext glade glade2 kernel-source libgcj libtool nasm qt-designer swig texinfo $ADDITIONAL_DEVEL_RPMS"

# Find -devel RPMs.

echo "Finding development RPMs..."
for rpm in `rpm -qa --qf "%{NAME}\n" | grep '\-devel$'`; do
    if [ -z "`rpm -q --whatrequires $rpm | grep '^gcc'`" ]; then
        devels="$rpm $devels"
    fi
done

# Check if we have some common others that are primarily for building.

for rpm in `LANG=C rpm -q --qf "%{NAME}\n" $DEVPKGS | grep -v 'not installed'`; do
    devels="$rpm $devels"
done

# Filter out what we want to keep.
for k in $KEEP_DEVEL_RPMS; do
    devels=$(echo "$devels" | sed "s| *\\b$k\\b||")
done
devels=$(echo "$devels" | sed "s|^ *||")

# Remove, if the user wishes so.

if [ -n "$devels" ]; then

    echo "Development RPMs found: $devels"
    if [ "$(whoami)" = "root" ]; then
	if [ "z$1" = "z-y" ]; then
	    REPLY=y
	else
            echo -n "Remove them? (y/N): "
            read
	fi
        case "$REPLY" in
            y|Y)
                echo "Removing: rpm -e --allmatches $devels"
                rpm -e --allmatches $devels
                ;;
            *)
                echo "Not removed."
                ;;
        esac
    else
        echo "Not running as root, skipping remove."
    fi
else
    echo "No development RPMs found."
fi
