#!/bin/bash

#
# fedora-diffrpm
# Diff contents of two RPMs
#
# Author:  Ville Skyttä <ville.skytta at iki.fi>
# License: GPL
# $Id: fedora-diffrpm,v 1.2 2004/01/29 19:00:39 scop Exp $

set -e

tmpdir=
diffopts=
trap cleanup EXIT

cleanup()
{
    set +e
    [ -z "$tmpdir" -o ! -d "$tmpdir" ] || rm -rf "$tmpdir"
}

usage()
{
    cat <<EOF
Usage: `basename $0` [diff-options] from-RPM to-RPM
  diff-options  Options passed to diff(1), in addition to -r (default: -Nu).
                The first argument not starting with a '-' ends diff-options.
EOF
}

while true ; do
    case "$1" in
        -*) diffopts="$diffopts $1" ;;
        *)  break ;;
    esac
    shift
done
if [ $# -lt 2 ] ; then
    usage
    exit 1
fi

tmpdir=`mktemp -d`
d1=`fedora-unrpm -qC "$tmpdir" "$1"`
d2=`fedora-unrpm -qC "$tmpdir" "$2"`
cd "$tmpdir"
diff -r ${diffopts:--Nu} "$d1" "$d2"
