#!/bin/bash

#
# fedora-unrpm
# Extract RPMs, "tar xvf" style
#
# Author:  Ville Skyttä <ville.skytta at iki.fi>
# License: GPL
# $Id: fedora-unrpm,v 1.3 2004/01/29 18:13:59 scop Exp $

usage()
{
    echo "Usage: `basename $0` [-q] [-C dir] RPMFILE..."
    echo "  -C dir    change to directory 'dir' before extracting"
}

extract()
{
    name=$(rpm -qp --qf "%{NAME}-%{VERSION}-%{RELEASE}" "$1")
    [ $? -ne 0 ] && echo "$name" && return 1

    (mkdir -p "$name" && \
    cd "$name" && \
    rpm2cpio "$1" \
    | cpio --quiet -idum$verbose 2>&1 \
    | sed "s|^\(\./\)\?|$name/|" && \
    cd ..)
}

if [ -z "$*" ]; then
    usage
    exit 1
fi


oldpwd="$PWD"
outputdir="$PWD"
verbose=v

while getopts "qC:" key ; do
    case "$key" in
        q) verbose= ;;
        C) outputdir="$OPTARG" ;;
        *) usage ; exit 1 ;;
    esac
done
shift $(( $OPTIND - 1 ))

if [ -n "$outputdir" -a "$outputdir" != "$PWD" ] ; then
    if ! cd "$outputdir" ; then
        usage
        exit 1
    fi
fi

for file in "$@"; do
    if ! echo "$file" | grep -q "^/" - ; then
        file="$oldpwd/$file"
    fi
    extract "$file"
done
