#!/bin/bash

#
# fedora-diffrpm
# Diff contents of two RPMs
#
# Author:  Ville Skyttä <ville.skytta at iki.fi>
# License: GPL
# $Id: fedora-diffrpm,v 1.5 2004/10/07 19:04:29 scop Exp $

cat <<EOF >&2
Warning: fedora-diffrpm is deprecated, use fedora-diffarchive instead."
EOF
sleep 2

fedora-diffarchive "$@"
