#!/bin/sh

# rpmls -- List contents of rpm packages
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

unset CDPATH

owner=
if [ "$1" = "-l" ] ; then
    owner='%-8{fileusername} %-8{filegroupname} '
    shift
fi
qf="[%-11{filemodes:perms} $owner%{filenames}\\n]"

for arg in "$@" ; do
    case "$arg" in
        http://*|https://*|ftp://*)
            rpm -qp --qf="$qf" "$arg"
            ;;
        *.[rs]pm)
            # dirname/basename: workaround for #250990
            cd "$(dirname "$arg")"
            rpm -qp --qf="$qf" "$(basename "$arg")"
            cd - >/dev/null 2>&1
            ;;
        *)
            rpm -q --qf="$qf" "$arg"
    esac
done
